### ISSUE TITLE
Replace dispatcher slider by a button with spinner

### ISSUE THREAD

**Issue by raiseerco** [lenstags/Lenstags#37]
Right now we have this function working okay:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/6036099/212329447-aa1f3fbb-1337-4752-b0c5-bb4ccbd1a205.png">

- We click the slider and the enable dispatcher tx is fired on metamask (ask for sign and confirm tx)
- When the wallet confirms, the slider status is not refreshed but if we refresh the page, the ui is updated ok

Solution approach:
- Replace the slider by a button with a spinner
![image](https://user-images.githubusercontent.com/6036099/212332057-f2e0b850-50fb-440a-a79c-f3dbe7f369e7.png)
- Once clicked, disable the clickability and update its tx status
![image](https://user-images.githubusercontent.com/6036099/212332227-ca28463c-774d-49e2-a223-0c4aa964ddd8.png)
- Once finished, show the successful status and show the disable button:
![image](https://user-images.githubusercontent.com/6036099/212332774-dbc5d3e4-f59b-4c0e-b37d-ada5b4c3e2a9.png)

**Comment by fedeloterstein** [comment]
@raiseerco estuve revisando y probando este ticket y me genera duda de donde sale el estado de la tx? eso viene de algun lado?
